### ISSUE TITLE
Convert profile to session presets feature

### ISSUE THREAD

**Issue by bettyblack23** [intechstudio/grid-editor#176]
- [x] When Convert profile to session preset button is clicked....
- [x] Convert selected profile to 16+1 session presets (Include system element)
- [x] Add tooltip and tooltip confirm for this feature
- [x] Tooltip and tooltip confirm text
- [x] TBD: Naming of the created session presets - "Profile name" [element number]
- [x] What if a preset already exists with the same name in SessionPreset?
- [x] Session Preset & Profile name input field width 

![Image](https://user-images.githubusercontent.com/32985513/224728719-6d452ea1-7f7b-4f69-90be-36bdc6904c6c.png)

**Comment by bettyblack23** [comment]
changes suggested by @kkerti 

![Image](https://user-images.githubusercontent.com/61327809/225956659-86f7f54c-88ae-4854-90ae-0273e758321b.png)

**Comment by narayb** [comment]
When trying to convert, gives error message, file path is correct.

![Image](https://user-images.githubusercontent.com/74784772/227224128-6a0d2ec2-9834-4cc7-830b-3d8d91012ea3.png)

Split action fails because of this error. Split folders are not created. Split jsons are not created.



![Image](https://user-images.githubusercontent.com/74784772/227251534-0eeefe03-5710-46ee-906f-e7121dac9993.png)
