### ISSUE TITLE
Midi monitor should detect 14-bit Control Changes

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#187]

**Comment by narayb** [comment]
MIDI monitor correctly detects 14-bit messages and highlights them as so in the MIDI monitor view.

Debug MIDI monitor view works differently than before. Unsure if intentional.

new:

![Image](https://user-images.githubusercontent.com/74784772/235135280-fa3cbdd8-0002-4208-b2a7-11306f91c0f9.png)


old:

![Image](https://user-images.githubusercontent.com/74784772/235135592-ca670064-e3b7-45ba-ad7a-461130b6fdca.png)
