### ISSUE TITLE
Bug, ver. 1.2.31: can't initialize an array

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#192]
See what this action in a PBF4 button init event:

<img width="550" alt="image" src="https://user-images.githubusercontent.com/303693/226125827-0441c229-b96b-4340-ac7d-34ef7dd3e2b9.png">

is compiled into:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/303693/226125846-f0aae8f7-3fab-4579-b024-887fa5d3868d.png">

Thanks.

**Comment by SukuWc** [comment]
![image](https://user-images.githubusercontent.com/32985513/230308598-afcb0228-793b-4274-ac6f-0e34bc09e1a1.png)

I just tested it in the grid editor and in the official lua RELP, in seems to work fine... Maybe the problem is that Lua indexes array starting from 1 by default, please try the following example!

```
local a, b = 1, {1,2,3}

print("Second", b[2])
```
