### ISSUE TITLE
RFC: Profile Cloud: ordering, file navigation, renaming, etc.

### ISSUE THREAD

**Issue by kkerti** [intechstudio/grid-editor#395]
Current Profile Cloud is cool, it has huuuge opportunities, GG so far.

The current design in the left panel should be revised to better support working with many files. Some parts are important and should be in focus on top: local, others for backup and sharing: PC.

get design best practices from:
- mac os finder file browser (how folder / file creation happens, renames, etc.)
- windows file browser (how folder / file creation happens, renames, etc.)
- other ???

Topics:
- When working on local profiles, renaming a profile will make the given profile "disappear" based on filtering
- Sort by date would come in handy, to see on top the latest changes
- ...

**Comment by giacecco** [comment]
Unless I am getting the UI dramatically wrong, the browser of the profile cloud is lacking major obvious features, e.g.:
- how do I list just my own profiles?
- how do I overwrite a profile of mine without creating a new one?
- if a grid device is currently selected - say a PBF4 - why does the browser show profiles for other kind of devices like the EN16? I should not need to filter them out, because it is obvious I can't use them with the current device

**Comment by kkerti** [comment]
> * how do I list just my own profiles?

Recently did this!

> * how do I overwrite a profile of mine without creating a new one?

In current Editor version, on the profile cloud panel, bottom down you can see the profile description and couple icons. There is an "overwrite" icon which does what you described.

> * if a grid device is currently selected - say a PBF4 - why does the browser show profiles for other kind of devices like the EN16? I should not need to filter them out, because it is obvious I can't use them with the current device

I think we didn't do such filtering yet, but working to add a better search field on the profile cloud panel - that might solve this moving forward. 

Any issue in relation to these persist - or you find the experience subpar -, please open a new ticket.
