### ISSUE TITLE
[RFC] MIDI NRPN Actionblock

### ISSUE THREAD

**Issue by SukuWc** [intechstudio/grid-editor#734]
https://en.wikipedia.org/wiki/NRPN

Nrpn allows the extension of control parameters beyond CC 0-127
MSB and LSB Controller numbers are sent first to address the control element then MSB and optionally LSB is sent for the control value!

![image](https://github.com/intechstudio/grid-editor/assets/32985513/a55e95a1-54a5-4095-93af-63d0d6cabde7)

This actionblock should send 
- 3 separate gms() calls for (14bit address, 7bit value) or 
- 4 separate gms() calls for (14bit address, 14bit value) controls

No firmware modification required as far as I see!

What do you think? Is this widely supported by hardware and DAW's?

**Comment by ctyz3n** [comment]
If the Intech devices had this,  then I'd buy them in a second.  A ton of hardware supports NRPNs, but it's not always documented, or people get confused by it.  It's actually much simpler than it seems. 

Any implementation sound include the Null calls to reset the open NRPN though (127,127), otherwise it stays open. 

JD-Xi is a good example of a modern synth with the ability for extensive use of NRPNs, but the Midi Documentation doesn't include these values.  The vast majority of parameters that aren't available on the front panel are available by NRPN and have been determined by the user base. The values are available if you look well enough. [Search for JD-Xi undocumented NRPNs].

**Comment by ctyz3n** [comment]
I should also add that some folks have found a way to implement a good middle ground for NRPNs that requires less bits.  Basically, rather than 7 bits = 0-127 [Coarse / low resolution Midi] or 14 bits = 0-16384 [fine / high resolution Midi, you can also use a compromise between the 2 that use 10 or 12 bits [med. Fine / medium resolution Midi].

Here's a YouTube video of a DIY product that has tackled this well. 

https://youtu.be/wFKIMYvxpFk?si=i-LivZstItOl6Rvy

**Comment by kkerti** [comment]
@SukuWc this was also bumped on discord and on the forum if I can recall correctly, so we should def do this!
